version: '3.6'

services:

  api:
    restart: always
    build: .
    links:
      - mysql
      - redis
    ports:
      - 5001:5000
    volumes:
      - .:/app
    command: python manager.py runserver
    environment:
      MYSQL_USER: root
      MYSQL_PWD: root

  mysql:
    build:
      context: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - 3308:3306

  redis:
    image: redis:4-alpine
    container_name: redis-car-rental
    ports:
      - 6379:6379
